# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{linkup}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Lindley"]
  s.date = %q{2010-02-06}
  s.description = %q{From: http://daringfireball.net/2009/11/liberal_regex_for_matching_urls}
  s.email = %q{jim@jimlindley.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "doc/ruby_regex.rb",
     "doc/sample_lines.txt",
     "lib/linkup.rb",
     "linkup.gemspec",
     "test/test_helper.rb",
     "test/test_linkup.rb"
  ]
  s.homepage = %q{http://github.com/jlindley/linkup}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Link bare urls in text.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_linkup.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

